
package com.demo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserImple", targetNamespace = "http://jdk.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserImple {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserById", targetNamespace = "http://jdk.demo.com/", className = "com.demo.client.FindUserById")
    @ResponseWrapper(localName = "findUserByIdResponse", targetNamespace = "http://jdk.demo.com/", className = "com.demo.client.FindUserByIdResponse")
    @Action(input = "http://jdk.demo.com/UserImple/findUserByIdRequest", output = "http://jdk.demo.com/UserImple/findUserByIdResponse")
    public String findUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
