
package com.demo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserImpleService", targetNamespace = "http://jdk.demo.com/", wsdlLocation = "http://192.168.0.102:8881/User?wsdl")
public class UserImpleService
    extends Service
{

    private final static URL USERIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException USERIMPLESERVICE_EXCEPTION;
    private final static QName USERIMPLESERVICE_QNAME = new QName("http://jdk.demo.com/", "UserImpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.102:8881/User?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERIMPLESERVICE_WSDL_LOCATION = url;
        USERIMPLESERVICE_EXCEPTION = e;
    }

    public UserImpleService() {
        super(__getWsdlLocation(), USERIMPLESERVICE_QNAME);
    }

    public UserImpleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERIMPLESERVICE_QNAME, features);
    }

    public UserImpleService(URL wsdlLocation) {
        super(wsdlLocation, USERIMPLESERVICE_QNAME);
    }

    public UserImpleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERIMPLESERVICE_QNAME, features);
    }

    public UserImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserImple
     */
    @WebEndpoint(name = "UserImplePort")
    public UserImple getUserImplePort() {
        return super.getPort(new QName("http://jdk.demo.com/", "UserImplePort"), UserImple.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserImple
     */
    @WebEndpoint(name = "UserImplePort")
    public UserImple getUserImplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jdk.demo.com/", "UserImplePort"), UserImple.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERIMPLESERVICE_EXCEPTION!= null) {
            throw USERIMPLESERVICE_EXCEPTION;
        }
        return USERIMPLESERVICE_WSDL_LOCATION;
    }

}
